import javax.swing.JFrame;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chinmay pc
 */
public class empview extends javax.swing.JFrame {
    private JTable table;

    /**
     * Creates new form empview
     */
    public empview() {
        DefaultTableModel model;
        initComponents();
        model=(DefaultTableModel)jTable2.getModel();
        
        
      //  Show_users_in_JTable();
    }
    private void fetch()
	{
		try {
			Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root" , "Chinmay@99");
			String q2 ="select * from emp1 ";
			
			ResultSet rs = null;
			jTable2.setModel(DbUtils.resultSetToTableModel(rs));
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
   
    
             
             
             
             
             

/*

public Connection getConnection()
    {
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/db", "root", "Chinmay@99");
            return con;
         
        }catch(SQLException e){
          return null;
        }
         public ArrayList<emp>getempList()
    {        ArrayList<emp>empList= new ArrayList<>();
    Connection connection = getConnection();
    String query ="";
    Statement st;
    ResultSet rs;
    
        try {
            st =connection.createStatement();
            rs = st.executeQuery(query);
            user u;
            while(rs.next())
            {
                u = new user(rs.getInt(""));
                empList.add(u);
            }
        } catch (SQLException e) {
        }
return empList;
    }
           public void Show_users_in_JTable()
    {ArrayList<user>list =empList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_users.getModel();
            
    Object[] row = new Object[4];
    for(int i =0;i<list.size();i++)
    {
        row[0]=list.get(i).getName();
        row[1]=list.get(i).getOpeningQuantity();
        row[2]=list.get(i).getConsumptionperday();
        row[3]=list.get(i).getDeliverySchedule();
        row[4]=list.get(i).getReceivedToday();
        row[5]=list.get(i).getConsumedToday();
        row[6]=list.get(i).getClosingQuantity();
        row[7]=list.get(i).getCoverage();
        row[8]=list.get(i).getReorderingLevel();
        row[9]=list.get(i).getReorderingQuantity();
        model.addRow(row);
    }
    }
  public void executeSQLQuery(String query,String message)
           {
           
        Connection con = getConnection();
        Statement st;
        try{st=con.createStatement();
        if(st.executeUpdate(query) == 1)
        {
        DefaultTableModel model = (DefaultTableModel)jTable_Display_users.getModel();
        model.setRowCount(0);
        Show_users_in_JTable();
        JOptionPane.showMessageDialog(null,"Data"+message+"Successfully");
        }else{
            JOptionPane.showMessageDialog(null,"Data Not" +message);
        }
            
        }catch(HeadlessException | SQLException ex){
        }
        
        
        
    }
  */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_i = new javax.swing.JButton();
        jTextFieldeid = new javax.swing.JTextField();
        jTextFieldln = new javax.swing.JTextField();
        jTextField_cpd = new javax.swing.JTextField();
        jTextField_ds = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_d = new javax.swing.JButton();
        jButton_u = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldrpn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldfn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_up = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_i.setText("Insert");
        jButton_i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_iMouseClicked(evt);
            }
        });
        jButton_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iActionPerformed(evt);
            }
        });

        jLabel2.setText("Employee id");

        jLabel3.setText("First name");

        jLabel4.setText("Designation");

        jLabel1.setText("Last name");

        jButton_d.setText("Delete");
        jButton_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_dMouseClicked(evt);
            }
        });
        jButton_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dActionPerformed(evt);
            }
        });

        jButton_u.setText("Display Table");
        jButton_u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_uMouseClicked(evt);
            }
        });
        jButton_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_uActionPerformed(evt);
            }
        });

        jLabel5.setText("Projectname");

        jLabel6.setText("Salary");

        jButton1.setText("Clear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employeeid", "FirstName", "LastName", "Designation", "Salary", "ProjectName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton_up.setText("Update");
        jButton_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_upMouseClicked(evt);
            }
        });
        jButton_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_upActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_d, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(10, 10, 10)))
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldeid, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                        .addComponent(jTextField_ds)
                                        .addComponent(jTextField_cpd)
                                        .addComponent(jTextFieldrpn)
                                        .addComponent(jTextFieldfn)
                                        .addComponent(jTextFieldln)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jButton_up))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_i)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_u)))
                        .addGap(81, 81, 81)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldrpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_d)
                    .addComponent(jButton_i)
                    .addComponent(jButton_up))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_u)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 142, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iActionPerformed
     
        
        
    }//GEN-LAST:event_jButton_iActionPerformed

    private void jButton_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_dMouseClicked
     
       int row = jTable2.getSelectedRow();

       
       
       //database delete
                    String selected = jTable2.getModel().getValueAt(row, 0).toString();
String sql="delete from emp1 where eid="+selected;



            
            {

//                

                try {
                    Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root" , "Chinmay@99");
		 PreparedStatement pst ;
                    pst=myConn.prepareStatement(sql);
                    pst.execute(); do {
    ((DefaultTableModel) jTable2.getModel()).removeRow(jTable2.getSelectedRows()[0]);
} while (jTable2.getSelectedRowCount() > 0);  
                             
      JOptionPane.showMessageDialog(jButton_d, "Deleted!!!!");
                   fetch();
                                             
                     
                }
                catch (SQLException w) {
                    JOptionPane.showMessageDialog(this, "Connection Error!");
                }
                    
            }
       
     
	
    }//GEN-LAST:event_jButton_dMouseClicked

    private void jButton_iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_iMouseClicked
          String s= jTextFieldeid.getText();
     String s1 = jTextFieldfn.getText();
     String s2= jTextFieldln.getText();
     String s3= jTextField_ds.getText();
     String s4 = jTextField_cpd.getText();
     String s5= jTextFieldrpn.getText();
     
        
        
        try{Connection con=DriverManager.getConnection("jdbc:mysql://localhost/db", "root", "Chinmay@99");
       PreparedStatement ps= con.prepareStatement("insert into emp1 values(?,?,?,?,?,?)");
        
            ps.setString(1,s);
            ps.setString(2,s1);
            ps.setString(3,s2);
            ps.setString(4,s3);
            ps.setString(5,s4);
            ps.setString(6,s5);
            int rs  = ps.executeUpdate();
    
        JOptionPane.showMessageDialog(jButton_i, "Successfully Inserted!!!!");
     jTextFieldeid.setText(null);
     jTextFieldfn.setText(null);
     jTextFieldln.setText(null);
     jTextField_ds.setText(null);
     jTextField_cpd.setText(null);
     jTextFieldrpn.setText(null);
           
       } catch (SQLException ex) {
            Logger.getLogger(empview.class.getName()).log(Level.SEVERE, null, ex);
        }
                try {
					Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root" , "Chinmay@99");
					String q2 ="select * from emp1";
					PreparedStatement ps= (PreparedStatement) myConn.prepareStatement(q2);
					ResultSet rs=ps.executeQuery(q2);
					jTable2.setModel(DbUtils.resultSetToTableModel(rs));
					
					
					
				} catch (SQLException e1) {
            // TODO Auto-generated catch block

				}
    }//GEN-LAST:event_jButton_iMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      JOptionPane.showMessageDialog(jButton1, "Cleared!!!!");
     jTextFieldeid.setText(null);
     jTextFieldfn.setText(null);
     jTextFieldln.setText(null);
     jTextField_ds.setText(null);
     jTextField_cpd.setText(null);
     jTextFieldrpn.setText(null);  
     
				
				 
        
					
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       String s= jTextFieldeid.getText();
        DefaultTableModel model;
        
        model=(DefaultTableModel)jTable2.getModel();
        jTextFieldeid.setText(String.valueOf(model.getValueAt(jTable2.getSelectedRow(),0)));
        jTextFieldfn.setText(String.valueOf(model.getValueAt(jTable2.getSelectedRow(),1)));
        jTextFieldln.setText(String.valueOf(model.getValueAt(jTable2.getSelectedRow(),2)));
        jTextField_ds.setText(String.valueOf(model.getValueAt(jTable2.getSelectedRow(),3)));
        jTextField_cpd.setText(String.valueOf(model.getValueAt(jTable2.getSelectedRow(),4)));
        jTextFieldrpn.setText(String.valueOf(model.getValueAt(jTable2.getSelectedRow(),5)));
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_upMouseClicked
       DefaultTableModel model;
        
        model=(DefaultTableModel)jTable2.getModel();
        model.setValueAt(jTextFieldeid.getText(),jTable2.getSelectedRow(),0);
        model.setValueAt(jTextFieldfn.getText(),jTable2.getSelectedRow(),1);
        model.setValueAt(jTextFieldln.getText(),jTable2.getSelectedRow(),2);
        model.setValueAt(jTextField_ds.getText(),jTable2.getSelectedRow(),3);
        model.setValueAt(jTextField_cpd.getText(),jTable2.getSelectedRow(),4);
        model.setValueAt(jTextFieldrpn.getText(),jTable2.getSelectedRow(),5);
        try {
            Connection myConn;
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root" , "Chinmay@99");
             int row = jTable2.getSelectedRow();
             String selected = jTable2.getModel().getValueAt(row, 0).toString();
            String query = "update emp1 set eid='"+jTextFieldeid.getText()+"',fn='"+jTextFieldfn.getText()+"',ln='"+jTextFieldln.getText()+"',des='"+jTextField_ds.getText()+"',sal='"+jTextField_cpd.getText()+"',pn='"+jTextFieldrpn.getText()+"'where eid="+selected;
					
					PreparedStatement pst ;
                    pst=myConn.prepareStatement(query);
                    pst.execute();
                                       
                                        JOptionPane.showMessageDialog(jButton_up, "Updated!!!!");
					 fetch();
                                      
     
        } catch (SQLException ex) {
            Logger.getLogger(empview.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     
    }//GEN-LAST:event_jButton_upMouseClicked

    private void jButton_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_upActionPerformed

    private void jButton_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_uActionPerformed

    }//GEN-LAST:event_jButton_uActionPerformed

    private void jButton_uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_uMouseClicked
try {
					Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root" , "Chinmay@99");
					String q2 ="select * from emp1";
					PreparedStatement ps= (PreparedStatement) myConn.prepareStatement(q2);
					ResultSet rs=ps.executeQuery(q2);
					jTable2.setModel(DbUtils.resultSetToTableModel(rs));
					
					
					
				} catch (SQLException e1) {

				}
    }//GEN-LAST:event_jButton_uMouseClicked

    private void jButton_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dActionPerformed
     
    }//GEN-LAST:event_jButton_dActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_d;
    private javax.swing.JButton jButton_i;
    private javax.swing.JButton jButton_u;
    private javax.swing.JButton jButton_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_cpd;
    private javax.swing.JTextField jTextField_ds;
    private javax.swing.JTextField jTextFieldeid;
    private javax.swing.JTextField jTextFieldfn;
    private javax.swing.JTextField jTextFieldln;
    private javax.swing.JTextField jTextFieldrpn;
    // End of variables declaration//GEN-END:variables
}
