import javax.swing.JFrame;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chinmay pc
 */
public class project1 extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    public project1() {
        initComponents();
        DefaultTableModel model;
        model=(DefaultTableModel)jTable2.getModel();
          
       
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
String d1 = sdf.format(dateChooserCombo_sd.getSelectedDate());
String d2 = sdf.format(dateChooserCombo_ed.getSelectedDate());
    }
 private void fetch()
	{
		try {
			Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root" , "Chinmay@99");
			String q2 ="select * from project ";
			
			ResultSet rs = null;
			jTable2.setModel(DbUtils.resultSetToTableModel(rs));
			
		} catch (SQLException e) {
                    // TODO Auto-generated catch block

		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField60 = new javax.swing.JTextField();
        jTextField102 = new javax.swing.JTextField();
        jTextField106 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jTextField155 = new javax.swing.JTextField();
        jComboBox49 = new javax.swing.JComboBox<>();
        jComboBox50 = new javax.swing.JComboBox<>();
        jComboBox51 = new javax.swing.JComboBox<>();
        jComboBox52 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField140 = new javax.swing.JTextField();
        jTextField141 = new javax.swing.JTextField();
        jTextField142 = new javax.swing.JTextField();
        jTextField143 = new javax.swing.JTextField();
        jTextField144 = new javax.swing.JTextField();
        jTextField145 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField61 = new javax.swing.JTextField();
        jTextField103 = new javax.swing.JTextField();
        jTextField107 = new javax.swing.JTextField();
        jTextField118 = new javax.swing.JTextField();
        jTextField126 = new javax.swing.JTextField();
        jTextField130 = new javax.swing.JTextField();
        jTextField134 = new javax.swing.JTextField();
        jTextField137 = new javax.swing.JTextField();
        jTextField146 = new javax.swing.JTextField();
        jTextField147 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jComboBox43 = new javax.swing.JComboBox<>();
        jTextField169 = new javax.swing.JTextField();
        jComboBox73 = new javax.swing.JComboBox<>();
        jComboBox74 = new javax.swing.JComboBox<>();
        jComboBox75 = new javax.swing.JComboBox<>();
        jComboBox76 = new javax.swing.JComboBox<>();
        jComboBox77 = new javax.swing.JComboBox<>();
        jComboBox78 = new javax.swing.JComboBox<>();
        jComboBox79 = new javax.swing.JComboBox<>();
        jComboBox80 = new javax.swing.JComboBox<>();
        jComboBox81 = new javax.swing.JComboBox<>();
        jComboBox82 = new javax.swing.JComboBox<>();
        jComboBox83 = new javax.swing.JComboBox<>();
        jComboBox84 = new javax.swing.JComboBox<>();
        jComboBox85 = new javax.swing.JComboBox<>();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jTextField159 = new javax.swing.JTextField();
        jTextField164 = new javax.swing.JTextField();
        jTextField168 = new javax.swing.JTextField();
        jComboBox58 = new javax.swing.JComboBox<>();
        jComboBox59 = new javax.swing.JComboBox<>();
        jComboBox60 = new javax.swing.JComboBox<>();
        jComboBox61 = new javax.swing.JComboBox<>();
        jComboBox62 = new javax.swing.JComboBox<>();
        jComboBox63 = new javax.swing.JComboBox<>();
        jComboBox64 = new javax.swing.JComboBox<>();
        jComboBox65 = new javax.swing.JComboBox<>();
        jComboBox66 = new javax.swing.JComboBox<>();
        jComboBox67 = new javax.swing.JComboBox<>();
        jComboBox68 = new javax.swing.JComboBox<>();
        jComboBox69 = new javax.swing.JComboBox<>();
        jComboBox70 = new javax.swing.JComboBox<>();
        jComboBox71 = new javax.swing.JComboBox<>();
        jComboBox72 = new javax.swing.JComboBox<>();
        jLabel88 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("ACTUATOR CALCULATION-");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 310, 40));

        jLabel17.setText("REMARK 1");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel18.setText("REMARK 2");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextField60.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField60ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 650, -1));

        jTextField102.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField102ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField102, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 650, -1));

        jTextField106.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField106ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField106, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 650, -1));

        jLabel20.setText("DATA REMARK");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("MAIN PAGE");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 140, 50));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("PROCESS AND VALVE DATA-");
        jLabel21.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 40));

        jLabel78.setText("CONNECTION");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel79.setText("ND ");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel132.setText("RATE");
        getContentPane().add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel133.setText("MATERIAL");
        getContentPane().add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel134.setText("WELD END");
        getContentPane().add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(jTextField155, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 50, -1));

        jComboBox49.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 50, -1));

        jComboBox50.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox50, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 50, -1));

        jComboBox51.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 50, -1));

        jComboBox52.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox52, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 50, -1));

        jLabel24.setText("xt/FL^2/zy");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel25.setText("V-VALVE-OUT GAS STEAM[Ma]");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jTextField140.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField140ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField140, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 120, -1));

        jTextField141.setPreferredSize(new java.awt.Dimension(71, 20));
        getContentPane().add(jTextField141, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 120, -1));

        jTextField142.setPreferredSize(new java.awt.Dimension(71, 20));
        getContentPane().add(jTextField142, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 120, -1));

        jTextField143.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField143.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField143ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField143, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 120, -1));

        jTextField144.setPreferredSize(new java.awt.Dimension(71, 20));
        getContentPane().add(jTextField144, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 120, -1));

        jTextField145.setPreferredSize(new java.awt.Dimension(71, 20));
        getContentPane().add(jTextField145, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 120, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("3-WAY HEATING OR COOLONG WATER CONNECTION-");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 390, 40));

        jLabel22.setText("STEM[mm]");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel23.setText("SEAT[mm]");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel26.setText("SEALING[mm]");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel27.setText("F-SEAL[N]");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel28.setText("F-FRICTION[N]");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel29.setText("CAVITATION/FLASHING");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel30.setText("v ND VALVE IN[ms]");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel31.setText("v ND VALVE OUT[ms]");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        jLabel32.setText("v PIPE DOWNSTREAM[ms]");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel33.setText("lp P1-TRIM[dB(A)]");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jTextField61.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField61ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, -1));

        jTextField103.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField103ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField103, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 80, -1));

        jTextField107.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField107ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField107, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 80, -1));

        jTextField118.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField118.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField118ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField118, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 80, -1));

        jTextField126.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField126ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField126, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 80, -1));

        jTextField130.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField130ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField130, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 80, -1));

        jTextField134.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField134ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField134, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 80, -1));

        jTextField137.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField137ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField137, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 80, -1));

        jTextField146.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField146ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField146, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 80, -1));

        jTextField147.setPreferredSize(new java.awt.Dimension(71, 20));
        jTextField147.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField147ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField147, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 80, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ACCESSORIES PARAMETERS(OPTIONAL)-");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel122.setText("POST.CONFIGURATION");
        getContentPane().add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel123.setText("MOUNTING");
        getContentPane().add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel124.setText("BOOSTER");
        getContentPane().add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jLabel125.setText("TRAVEL TIME");
        getContentPane().add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        jLabel126.setText("AIR SET");
        getContentPane().add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel127.setText("SOLENOID VALVE");
        getContentPane().add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jLabel128.setText("LOCK-UP");
        getContentPane().add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel129.setText("ACCESSOR1");
        getContentPane().add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLabel130.setText("ACCESSOR2");
        getContentPane().add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jLabel131.setText("LIMIT SWITCH ");
        getContentPane().add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        jLabel135.setText("MASTER CERTIFICATE");
        getContentPane().add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        jLabel136.setText("FINAL CERTIFICATE");
        getContentPane().add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jLabel137.setText("GASKET");
        getContentPane().add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jComboBox43.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 50, -1));
        getContentPane().add(jTextField169, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 50, 20));

        jComboBox73.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox73, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 50, -1));

        jComboBox74.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox74, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 50, -1));

        jComboBox75.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox75, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 50, -1));

        jComboBox76.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox76, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 50, -1));

        jComboBox77.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox77, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 50, -1));

        jComboBox78.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox78, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 50, -1));

        jComboBox79.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox79, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 50, -1));

        jComboBox80.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox80, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 50, -1));

        jComboBox81.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox81, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 50, -1));

        jComboBox82.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox82, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 50, -1));

        jComboBox83.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox83, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 50, -1));

        jComboBox84.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox84, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 50, -1));

        jComboBox85.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox85, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 50, -1));

        jLabel107.setText("LEAKAGE");
        getContentPane().add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        jLabel108.setText("DPSHUT");
        getContentPane().add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        jLabel109.setText("ACTUATOR TYPE");
        getContentPane().add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        jLabel110.setText("AIR PRESSURE");
        getContentPane().add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        jLabel111.setText("FUNCTION");
        getContentPane().add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        jLabel112.setText("AIR FAILURE");
        getContentPane().add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jLabel113.setText("BALANCE PROPOSED");
        getContentPane().add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        jLabel114.setText("BALANCE SELECTED");
        getContentPane().add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, -1));

        jLabel115.setText("PACKING");
        getContentPane().add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        jLabel116.setText("SEALING");
        getContentPane().add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, -1, -1));

        jLabel117.setText("ACTUATOR PROPOSED");
        getContentPane().add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, -1));

        jLabel118.setText("ACTUATOR SELECTED");
        getContentPane().add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));

        jLabel119.setText("HAND-WHEEL");
        getContentPane().add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        jLabel120.setText("ACTUATOR DESIGN");
        getContentPane().add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, -1, -1));

        jLabel121.setText("ACTUATOR PAINTING");
        getContentPane().add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, -1, -1));

        jTextField159.setPreferredSize(new java.awt.Dimension(71, 20));
        getContentPane().add(jTextField159, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 50, -1));

        jTextField164.setPreferredSize(new java.awt.Dimension(71, 20));
        getContentPane().add(jTextField164, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 50, -1));
        getContentPane().add(jTextField168, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 50, -1));

        jComboBox58.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox58, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 50, -1));

        jComboBox59.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox59, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 50, -1));

        jComboBox60.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox60, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 50, -1));

        jComboBox61.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox61, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 50, -1));

        jComboBox62.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox62, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 50, -1));

        jComboBox63.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox63, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 50, -1));

        jComboBox64.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox64, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 50, -1));

        jComboBox65.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox65, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 50, -1));

        jComboBox66.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox66, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 50, -1));

        jComboBox67.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox67, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 50, -1));

        jComboBox68.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox68, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 50, -1));

        jComboBox69.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox69, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, 50, -1));

        jComboBox70.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox70, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 50, -1));

        jComboBox71.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox71, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 50, -1));

        jComboBox72.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox72, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 50, -1));

        jLabel88.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel88.setText("ACTUATOR PARAMETERS-");
        getContentPane().add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField60ActionPerformed

    private void jTextField102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField102ActionPerformed

    private void jTextField106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField106ActionPerformed

    private void jTextField140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField140ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField140ActionPerformed

    private void jTextField143ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField143ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField143ActionPerformed

    private void jTextField61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField61ActionPerformed

    private void jTextField103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField103ActionPerformed

    private void jTextField107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField107ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField107ActionPerformed

    private void jTextField118ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField118ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField118ActionPerformed

    private void jTextField126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField126ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField126ActionPerformed

    private void jTextField130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField130ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField130ActionPerformed

    private void jTextField134ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField134ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField134ActionPerformed

    private void jTextField137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField137ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField137ActionPerformed

    private void jTextField146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField146ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField146ActionPerformed

    private void jTextField147ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField147ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField147ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox43;
    private javax.swing.JComboBox<String> jComboBox49;
    private javax.swing.JComboBox<String> jComboBox50;
    private javax.swing.JComboBox<String> jComboBox51;
    private javax.swing.JComboBox<String> jComboBox52;
    private javax.swing.JComboBox<String> jComboBox58;
    private javax.swing.JComboBox<String> jComboBox59;
    private javax.swing.JComboBox<String> jComboBox60;
    private javax.swing.JComboBox<String> jComboBox61;
    private javax.swing.JComboBox<String> jComboBox62;
    private javax.swing.JComboBox<String> jComboBox63;
    private javax.swing.JComboBox<String> jComboBox64;
    private javax.swing.JComboBox<String> jComboBox65;
    private javax.swing.JComboBox<String> jComboBox66;
    private javax.swing.JComboBox<String> jComboBox67;
    private javax.swing.JComboBox<String> jComboBox68;
    private javax.swing.JComboBox<String> jComboBox69;
    private javax.swing.JComboBox<String> jComboBox70;
    private javax.swing.JComboBox<String> jComboBox71;
    private javax.swing.JComboBox<String> jComboBox72;
    private javax.swing.JComboBox<String> jComboBox73;
    private javax.swing.JComboBox<String> jComboBox74;
    private javax.swing.JComboBox<String> jComboBox75;
    private javax.swing.JComboBox<String> jComboBox76;
    private javax.swing.JComboBox<String> jComboBox77;
    private javax.swing.JComboBox<String> jComboBox78;
    private javax.swing.JComboBox<String> jComboBox79;
    private javax.swing.JComboBox<String> jComboBox80;
    private javax.swing.JComboBox<String> jComboBox81;
    private javax.swing.JComboBox<String> jComboBox82;
    private javax.swing.JComboBox<String> jComboBox83;
    private javax.swing.JComboBox<String> jComboBox84;
    private javax.swing.JComboBox<String> jComboBox85;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JTextField jTextField102;
    private javax.swing.JTextField jTextField103;
    private javax.swing.JTextField jTextField106;
    private javax.swing.JTextField jTextField107;
    private javax.swing.JTextField jTextField118;
    private javax.swing.JTextField jTextField126;
    private javax.swing.JTextField jTextField130;
    private javax.swing.JTextField jTextField134;
    private javax.swing.JTextField jTextField137;
    private javax.swing.JTextField jTextField140;
    private javax.swing.JTextField jTextField141;
    private javax.swing.JTextField jTextField142;
    private javax.swing.JTextField jTextField143;
    private javax.swing.JTextField jTextField144;
    private javax.swing.JTextField jTextField145;
    private javax.swing.JTextField jTextField146;
    private javax.swing.JTextField jTextField147;
    private javax.swing.JTextField jTextField155;
    private javax.swing.JTextField jTextField159;
    private javax.swing.JTextField jTextField164;
    private javax.swing.JTextField jTextField168;
    private javax.swing.JTextField jTextField169;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    // End of variables declaration//GEN-END:variables
}
